Update README.md
selfagency/microsoft-drop-ice pull request #429
Opened 2020-11-27 00:56 UTC by daemonspudguy

2020-12-04 06:12 UTC, HelenGezahegn requested changes

2020-12-04 06:12 UTC, HelenGezahegn commented on README.md
> +1.  Jacob A. Tice [@daemonspudguy](https://github.com/daemonspudguy) (Owner of Jacob A. Tice Media, human rights advocate)
Please move this before `Jacob Beard` to stay in alphabetical order. Thanks!

2020-12-07 23:17 UTC, HelenGezahegn approved these changes

2020-12-07 23:17 UTC, merged

2020-12-09 14:10 UTC, menum724 commented
Thank you Jacob.