Sign: Mia
selfagency/microsoft-drop-ice pull request #436
Opened 2021-04-20 08:16 UTC by ThatGeekyWeeb

2021-04-20 18:51 UTC, HelenGezahegn requested changes

2021-04-20 18:51 UTC, HelenGezahegn commented on README.md
> +1.  Mia [@thatgeekyweeb](https://github.com/thatgeekyweeb)
Hey Mia, do you have a last name? Please add it if you do!

2021-04-20 21:16 UTC, ThatGeekyWeeb commented on README.md
> +1.  Mia [@thatgeekyweeb](https://github.com/thatgeekyweeb)
There ya go!

2021-04-22 21:30 UTC, HelenGezahegn approved these changes
Thanks!

2021-04-22 21:31 UTC, merged